### ISSUE TITLE
Make this a GitHub template repository

### ISSUE THREAD

**Issue by moltar** [wemake-services/wemake-vue-template#1345]
https://help.github.com/en/articles/creating-a-template-repository

**Comment by sobolevn** [comment]
Thanks for the suggestion! Unfortunately that's not the case for this project. Because:
1. Github templates assume that the whole repo is the template. But, we store the actual template in `template/` folder
2. Github cannot use template variables

So, I am closing this issue for now. Maybe someday these features will be supported by Github.
