### ISSUE TITLE
Classic mode for store/ is deprecated and will be removed in Nuxt 3.

### ISSUE THREAD

**Issue by alza54** [wemake-services/wemake-vue-template#1393]
Should I care about this warning? Is it hard to fix this warning with this template structure? If it is, how to suppress this warning?

**Comment by sobolevn** [comment]
Hm, I had a conversion with someone from the Nuxt core team not so long ago. We discussed that most possibly they will remove this working in the next versions. And keep the classic mode.

Why? Because this mode is required for a lot of tools like the one we use. https://github.com/nuxt/nuxt.js/issues/4935

**Comment by alza54** [comment]
Oki, thanks
